### ISSUE TITLE
Enable FULLSCREEN_API and add public API for it

### ISSUE THREAD

**Issue by annulen** [annulen/webkit#205]
Something like http://doc-snapshots.qt.io/qt5-5.7/qwebenginefullscreenrequest.html but without possiblity to move or copy request object in slot.

**Comment by Emdek** [comment]
Required API additions (from the most to the least important):
 * `QWebFullScreenRequest` class;
 * `void QWebPage::fullScreenRequested(QWebFullScreenRequest request)` signal;
 * `QWebSettings::FullScreenSupportEnabled` in `WebAttribute` enum (seems to be used to determine if fullscreen support should be advertised);
 * `QWebPage::ExitFullScreen` in `WebAction` enum.

**Comment by Emdek** [comment]
Some extra notes:
 * old fallback for video elements should be removed after landing proper support, as noted by @annulen;
 * since `QWebPage::ToggleVideoFullscreen` was already exposed earlier it might default to accepting request (QtWebEngine ignores them by default, but it doesn't make sense to require programmatically accept request which was also triggered programmatically);
 * `QWebFullScreenRequest` could expose `QWebElement` for which it was requested;
 * `QWebFullScreenRequest` could expose `reason`, which could allow to identify requests generated by `QWebPage::ToggleVideoFullscreen`  etc.;
 * consider method to programmatically request full screen for specified element, such request would be accepted by default.

**Comment by annulen** [comment]
>old fallback for video elements should be removed after landing proper support

Not in this release, fullscreen video with specialized widget may be life-saver for developers of embedded software. I doubt they are very interested in QtMM though, but this code can be used as example (like QtMM player itself)

>since QWebPage::ToggleVideoFullscreen was already exposed earlier it might default to accepting request (QtWebEngine ignores them by default, but it doesn't make sense to require programmatically accept request which was also triggered programmatically)

it's hard to implement correctly, but if you want to bite the bullet I'm not going to stop you :)

>QWebFullScreenRequest could expose QWebElement for which it was requested

sure, it's readily available

>QWebFullScreenRequest could expose reason, which could allow to identify requests generated by QWebPage::ToggleVideoFullscreen etc

that's hard to implement and will probably require modification of WebCore APIs

>consider method to programmatically request full screen for specified element, such request would be accepted by default.

same as with ToggleVideoFullscreen

**Comment by Emdek** [comment]
One more thing, adding support to *QtTestBrowser* (asking user what to using message box).
