### ISSUE TITLE
Building webkit on ppc64le.

### ISSUE THREAD

**Issue by sowani** [annulen/webkit#501]
Hi,

As part of my work on issues seen on PhantomJS (#480, #483), I am trying to clone webkit code and build it on ppc64le. However there is some JavaScriptCore/assembler code which should not get built on ppc64le but somehow getting in the way causing build to fail.

I compared this code with the "qtwebkit" source code in PhantomJS directory and saw a lot of difference (PhantomJS webkit directory does not have tests and examples, which is understood). So, is this webkit code already ported to (or written for considering) ppc64le? The webkit code that comes with PhantomJS builds without issues on ppc64le. Are there any special branches/versions maintained here for PhantomJS?

I am trying "cmake . -DPORT=Qt" to build webkit. If this code is supposed to get built on ppc64le without issues, am I using correct build command? Anything additional should be specified to cmake/make?

Thanks,
Atul.

**Comment by annulen** [comment]
>I compared this code with the "qtwebkit" source code in PhantomJS directory and saw a lot of difference

Of course. PhantomJS includes legacy QtWebKit that is based on WebKit branch from 2013, and qtwebkit-stable corresponds to 2016 at the moment.

>So, is this webkit code already ported to (or written for considering) ppc64le?

I guess nobody else works on ppc64le specifically, so there may be dragons. Please report issues that you cannot fix yourself.

As for "written considering" part, JavaScriptCore in theory should work on any architecture if CLoop (ENABLE_JIT=OFF) is used, but practice can be different.

>Are there any special branches/versions maintained here for PhantomJS?

AFAIK no, cc @Vitallium 

>I am trying "cmake . -DPORT=Qt" to build webkit

https://github.com/annulen/webkit/wiki/Building-QtWebKit-on-Linux

>If this code is supposed to get built on ppc64le without issues

It is not supposed unless you say us that your port is done :)

**Comment by sowani** [comment]
@annulen -- Thanks for clarifications - in fact that helps a lot in setting up my expectations to correct level. For some reason I was under impression that this particular fork of webkit will work "as is" with PhantomJS and hence I was expecting the latest code (2016) to get built on ppc64le. So looks like my understanding was wrong.

On PhantomJS github, I think I saw a mention of annulen/webkit having been revived to include updated webkit in upcoming release of PhantomJS (I think it is 2.5), so if that is correct, I am right in thinking that it will no more work on ppc64le "as is"? Because if they plan to utilize 2016 version, it will need porting first before it works on ppc64le.

**Comment by annulen** [comment]
WebKit on non-mainstream architectures is about self-service. For example, a substantial amount of work was required from me and a few other people to get MIPS JIT working in this branch, though legacy QtWebKit worked without problems. SH4 JIT will probably never work again. This happens because JSC is moving on fast, new JS standards are implemented and JIT engine is improved, so architecture support needs to be updated too.

To prevent such things from happening someone has to check if trunk works on particular arch from time to time. Now we have JSCOnly port in trunk, it makes it easy to test JSC without having full-blown Qt port updated to trunk, ICU is pretty much the only mandatory dependency of JSCOnly.

>it will need porting first before it works on ppc64le

I've posted the announcement more than a year ago, you replied that you would test it :)

https://lists.webkit.org/pipermail/webkit-qt/2016-January/004044.html

**Comment by sowani** [comment]
Aha! :) So that's it. All pieces have fallen in place! I will take up this work then. Sure, my response is still valid. :)

**Comment by annulen** [comment]
Please open new reports in case you have specific issues
