### ISSUE TITLE
Incorrect page width for plain text messages in Trojita

### ISSUE THREAD

**Issue by fturco** [annulen/webkit#511]
I noticed a problem with Qtwebkit-6.0 and the Trojita e-mail client.

Plain text messages without any corresponding HTML version are displayed with a page width of only 2 characters.

![trojita](https://cloud.githubusercontent.com/assets/5459866/24949259/38368f46-1f6d-11e7-9d04-359edcdf14c8.png)

This problem happens on both Trojita 0.7 and Trojita git. I suspect that this problem is due to having upgraded Qtwebkit from version 5.7.1 to version 6.0. Trojita developers think the problem may be caused by a regression in Qtwebkit.

My GNU/Linux distribution is Gentoo Linux.

Please also see [KDE bug 378684](https://bugs.kde.org/show_bug.cgi?id=378684).

**Comment by annulen** [comment]
Is it posible to get HTML test case where it reproduces?

**Comment by fturco** [comment]
I'm afraid I don't understand what you need exactly. Should I provide the HTML source of an e-mail that is affected by this problem perhaps?

**Comment by annulen** [comment]
If Trojita uses QWebView, it has to load some HTML into it. In case of plain text message, they generate it somehow or just load plain text as is, and maybe they also add custom style sheets (e.g. via `QWebSettings::setUserStyleSheetUrl` or `evaluateJavaScript`). If we determine what is loaded into QWebView actually, we will be able to reproduce bug without Trojita

Do you think you can try to debug it yourself by following Trojita's code?

**Comment by jktjkt** [comment]
Hi, Trojita upstream here. I suspect that the main reason for failing is that we're trying to undo QtWebKit's built-in QScrollArea by manipulating various layout and margins. Our code has worked with all versions of qtwebkit starting at 4.8.x (or 4.6.x?). Today, Trojita doesn't have any hard dependencies apart from Qt 5.2+ and cmake, so it should be easy to build and try this yourself. The relevant code is at https://github.com/jktjkt/trojita/blob/master/src/Gui/EmbeddedWebView.cpp#L118

**Comment by annulen** [comment]
@jktjkt Thanks for you help! I certainly can try to debug myself, just wanted to offload a bit of work :)

**Comment by annulen** [comment]
@jktjkt BTW, to undo built-in scrolling you can use `QWebPage::setPreferredContentsSize`, e.g. as it is done in https://github.com/annulen/webkit/blob/qtwebkit-stable/Tools/QtTestBrowser/webview.cpp#L103. Unfortunately in my fork there is a bug with painting backgrounds in this mode, see #472. Also I'm not sure if it can work without QGraphicsView

**Comment by elvisangelaccio** [comment]
Any news on this? Archlinux ships this new version of qt5-webkit in their main repositories, so there are many users affected.

**Comment by rapgro** [comment]
Reproducible for me. This issue landed in Fedora, too.

**Comment by darkbasic** [comment]
Hello everyone. I'm looking for an honest answer: do I need to change my favourite email client? After almost half an year without a fix/workaround I cannot stand it anymore: is a fix ever going to land? Thanks

**Comment by jktjkt** [comment]
@darkbasic , I believe that this depends on @annulen and distributions. We are simply using a component that has regressions; there's nothing that we could change in Trojita :(. Well, we might (and we will, eventually) switch to the QtWebEngine, but that's about all.

**Comment by annulen** [comment]
Actually no, it's because your code is using dirty hack which could be avoided by use of existing API. Anyway, fix exists and will be pushed soon

**Comment by jktjkt** [comment]
@annulen , I'm happy to hear that you've got a patch -- thanks! The solution you pointed out in https://github.com/annulen/webkit/issues/511#issuecomment-293538086 won't work for us because Trojita is using the widget based API and not a QGraphicsView. If there's something like that in `QWebView`, I will be very happy to port our code because it's an ugly workaround, indeed.

**Comment by darkbasic** [comment]
Distributions have **nothing** to do with this, because the bug is clearly upstream (even in latest released version). They simply cannot freeze the whole qt-webkit to an ancient version because of trojita: other apps need security fixes and the new features.

A good maintainer should have done the following:
- fix his code if he's doing something wrong
- otherwise properly fix the broken dependency (if he is able to)
- in the meantime workaround the issue until a proper fix lands
- when everything gets fixed contribute proper tests to qt-webkit to avoid that such issues will happen again in the future

Anyway I'm not here to teach anyone what a maintainer should or should not have done (I'm the first one who rarely do the right thing in such regard, so I really cannot point fingers), just please don't tell me that the issue depends on distributions because this is not true.

@annulen I'm glad to hear that there is a fix pending, can you please point me to it so I can apply it to my distribution's qt-webkit?

**Comment by kkofler** [comment]
Ping? You said 24 days ago that a fix exists, can we please have that fix so we can ship it in distributions?

**Comment by annulen** [comment]
@darkbasic @kkofler Please use 6faf11215e1af27d35e921ae669aa0251a01a1ab + 76420459a13d9440b41864c93cb4ebb404bdab55

**Comment by lupinix** [comment]
Fix imported in Fedora, fixed qt5-qtwebkit will be available within next hours in updates-testing repository for all supported Fedora releases.

**Comment by rapgro** [comment]
Thank you all. QtWebkit is alive. 👍
