### ISSUE TITLE
WebAssembly

### ISSUE THREAD

**Issue by jeprojects** [annulen/webkit#643]
Hi,

Just curious but does this support WebAssembly?

**Comment by annulen** [comment]
Not yet, will support after https://github.com/annulen/webkit/milestone/5 is reached

**Comment by annulen** [comment]
Out of curiosity, what is your use case for Wasm?

**Comment by jeprojects** [comment]
I have an web app that is using it.

I can test things if you like?

Is there a rough ballpark time when it will be available? Few months or?

**Comment by yhafri** [comment]
Hi @annulen 

Any update on [Qt for WebAssembly](https://doc.qt.io/qt-5/wasm.html)?
I was able to install `em++` on Windows as explained in the link. But when i tried to compile my QTWebkit app:

```
$ /path/to/qt-wasm/qtbase/bin/qmake
$ make
```
it failed because it couldn't find QTWebkit.

Thanks

**Comment by annulen** [comment]
This issue was about WASM support in QtWebKit itself (should work in qtwebkit-dev-wip branch now).

I don't think anyone tried building QtWebKit with emscripten, however it might be possible to do by following https://github.com/qtwebkit/qtwebkit/wiki/Building-static-libraries with addition of `-DENABLE_JIT=OFF`. It would probably be required to add new CPU and OS type defines for WASM. Note that pthreads support in emscripten is required. There may be other platform-specific issues as well.

That said, I don't see much reason in running a browser inside a browser beyond purely academic interest.
