### ISSUE TITLE
can I build with no icu

### ISSUE THREAD

**Issue by developernew123** [annulen/webkit#692]
the dlls of icu is very large and I don't need icu as I'm using some particular websites to test can I build without icu ?

**Comment by annulen** [comment]
You can use ICU with reduced data set. Easiest way is to confiugure ICU to use separate .dat file instead of embedding data into dll, and then replace this file.  See http://userguide.icu-project.org/icudata, http://apps.icu-project.org/datacustom/

In theory it should be ok to use ICU without any data file, however WebKit is known to crash in this case (IIRC it happens somewhere inside ICU). Patches to fix this are welcome (it's probably not ICU bug but wrong API usage inside WebKit)

Building without ICU at all is not supported, see https://github.com/annulen/webkit/wiki/FAQ#why-so-many-dependencies-besides-qt

**Comment by annulen** [comment]
It's also possible to use limited configuration of ICU itself to decrease size, if you disable ENABLE_DATE_AND_TIME_INPUT_TYPES and ENABLE_INTL (see https://bugs.webkit.org/show_bug.cgi?id=154483)
