### ISSUE TITLE
[FYI]: rekonq

### ISSUE THREAD

**Issue by RJVB** [annulen/webkit#694]
Just a FYI/reminder: KDE used to have a simple, clean(ish) alternative to Konqueror, Rekonq, which is reminiscent of Apple's Safari.

The devs created a frameworks branch which has been unmaintained for a few years but it wasn't hard to get it to build with the current KF5 frameworks, Qt 5.8 and QtWebKit 5.212alpha2 : https://cgit.kde.org/rekonq.git?h=frameworks .

It would be great to see this one rebooted too, as a showcase of QtWebKit. While Konqueror has the advantage that you can switch backends on the fly, Rekonq uses QtWebkit directly, not via kde-webkit.

**Comment by RJVB** [comment]
![image](https://user-images.githubusercontent.com/1756884/34081072-2e6a48fa-e348-11e7-9fe2-7e4131dca9e9.png)

**Comment by annulen** [comment]
Great, feel free to proceed with this

**Comment by RJVB** [comment]
Sure, and anyone else please feel free the chip in. Writing browsers isn't exactly my forte nor what keeps me awake at night ;)

**Comment by annulen** [comment]
It make more sense to support alive projects instead, e.g. https://otter-browser.org/ or http://qutebrowser.org/

**Comment by annulen** [comment]
Or make brand new non-toy browser based on WebKit2

**Comment by annulen** [comment]
Because all WK1-based browsers suffer from same issues with responsiveness, crash tolerance, accumulation of memory fragmentation. Also, to some extent process separation even without sandboxing reduces attack surface and thus makes browser more secure. When WebAssembly comes into play it's crucial for performance to use custom signal handlers, however in case of WK1 this can get in conflict with user's signal handlers.

WK1 is fine choice for pretty-much everything but a web browser in complete sense of this word

**Comment by RJVB** [comment]
I don't know if it's fair to call Rekonq a toy browser. But the Otter browser project looks interesting and worth checking out. I used to be an Opera user (esp. before they started using WebKit, though O:-) )

R.

**Comment by annulen** [comment]
>I don't know if it's fair to call Rekonq a toy browser.

This was a reference to existing browsers based on Qt WK2, which are either toy or mobile (most likely the latter fall into first category as well), not to Rekonq

**Comment by RJVB** [comment]
>WK1 is fine choice for pretty-much everything but a web browser in complete sense of this word

You probably shouldn't be using any browser that's not (based on) Chrome or Firefox for sensitive things like banking. But they're probably fine for non-sensitive tasks (even the occasional FB post) you don't do in your main browsing session.

**Comment by annulen** [comment]
>You probably shouldn't be using any browser ... for sensitive things like banking.

FTFY

I wonder why did you pick security argument, it was intentionally put last in the list

**Comment by RJVB** [comment]
>>You probably shouldn't be ... banking.
>
>FTFY

T,FTFY2 since apparently you have someone at a bank to do if for you ;)


>I wonder why did you pick security argument, it was intentionally put last in the list

Because it's the only one you shouldn't be too tolerant. Responsiveness is subjective, crashing will depend on your use pattern and not really an issue if you don't count on the browser to run very long sessions (which also applies to the memory argument).

**Comment by annulen** [comment]
Also, single-process model doesn't really fit for usage qith multiple tabs and/or windows, because all pages share same event loop which also happens to be the main loop of Qt GUI

>Responsiveness is subjective

No, it has an objective component

**Comment by RJVB** [comment]
>Also, single-process model doesn't really fit for usage qith multiple tabs and/or windows, because all pages share same event loop which also happens >to be the main loop of Qt GUI

Can't you have an event loop per thread? Either way, if you want really separate and fully independent event loops you (probably) cannot have tabs but only open each new page in a new window that's actually a new process (I think Dolphin works like that). 
And what's to stop anyone from implementing a slave application that runs as a background process doing the rendering into an offscreen buffer in shared memory which is then rendered by a shell?

>>Responsiveness is subjective
>
>No, it has an objective component

The fact that you can quantify it doesn't mean everyone shares the same mapping to a qualititave slow/fast scale. 

I just built the Otter browser and gave it a whirl. It feels pretty snappy to me. The only thing that looks odd nowadays is to see images being painted from the top down (e.g. https://www.son-video.com/calendrier-de-l-avent-2017).

**Comment by annulen** [comment]
>Can't you have an event loop per thread?

To do this I need to have threads in the first place, but WebCore is inherently single-threaded [*][**]

>Either way, if you want really separate and fully independent event loops you (probably) cannot have tabs but only open each new page in a new window that's actually a new process (I think Dolphin works like that).

In fact, Uzbl was doing tabs with separate processes by providing sort of window manager for tab windows

>And what's to stop anyone from implementing a slave application that runs as a background process doing the rendering into an offscreen buffer in shared memory which is then rendered by a shell?

That's what WebKit2 is all about. Just done more cleverly, allowing to use lower number of background processes then tabs, and providing sophisticated API for controlling execution of these processes

>I just built the Otter browser and gave it a whirl. It feels pretty snappy to me

This doesn't necessary mean things cannot work better. Also it easy to be snappy on snappy pages, when you have to browse through something poorly implemented and bloated, WK2 wins easily

[*] Except JS Workers, each of them runs in a separate native thread with it's own JS VM which doesn't have access to DOM. So most of code on the Web has to run on main thread, because it wants DOM access
[**] Except in iOS port, which supports (supported?) running WebCore in thread in WK1 mode. Of course it means lots of additional locking, and this code path was never tested by anyone if it can be useful outside of iOS port. Now iOS provides WK2 as primary API, WK1 is provided for compatibility with old apps only

**Comment by annulen** [comment]
Closing this, as resurrecting Reconq is definitely out of scope for this project. You may want to use different media, e.g. KDE communication channels
