### ISSUE TITLE
Is this project still being actively developed?

### ISSUE THREAD

**Issue by mlutken** [annulen/webkit#797]
See headline :)

**Comment by FVerbum** [comment]
Please answer directly and exactly.

**Comment by cgilles** [comment]
I would to know also the status of this project. Thanks in advance...

**Comment by herbmillerjr** [comment]
Whenever you're ready to get the ball rolling, @annulen, I'm ready to help any way I can. Writing layout tests, fixing bugs, etc.

**Comment by kaamui** [comment]
Hello @annulen,

first I would like to thank you for your amazing work as it is saving us a lot of time and helpiong us avoid a lot of issues porting [OpenBoard](https://github.com/OpenBoard-org/OpenBoard) to qt5.9 with the web engine. Indeed, a lot of our core classes are dependent of the QGraphicsWebView class provided by the webkit but simply not supported at all by the WebEngine ([source](https://doc.qt.io/qt-5/qtwebenginewidgets-qtwebkitportingguide.html)) <- another use case for your wiki :)

I read [here](https://lists.qt-project.org/pipermail/development/2017-May/029795.html) that it could be re-integrated in the official releases of qt, as an option. But all the news stop around 2017 about all this stuff.

I was just wondering if you had any information to share with us, to help me/us understand if anything is in the making or if you simply have no more time to handle all of this, etc ..

I wonder if I I make the long term choice by maintaining the use of the webkit in our project, and also if I can hope to see the webkit to be reconsidered by qt. The fact that your work is been officially part of the qt git repositories since the discussion is a positive sign, but since almost no more things were added since 2017, I would love to know what's happening. 

Thank you in advance.

**Comment by annulen** [comment]
>First I would like to thank you for your amazing work as it is saving us a lot of time and helping us avoid a lot of issues porting OpenBoard to qt5.9 with the web engine. Indeed, a lot of our core classes are dependent of the QGraphicsWebView class provided by the webkit but simply
not supported at all by the WebEngine (source) <- another use case for your wiki :)

QGraphicsView itself is pretty much obsolete technology. You should probably migrate to QML

**Comment by kaamui** [comment]
> QGraphicsView itself is pretty much obsolete technology. You should probably migrate to QML

Did you mean QGraphicsWebView ? I'm going to assume you really meant QGraphicsView :  

I'm not familiar with QML, so I'm not sure where it would be a better thing and where not. OpenBoard is a cross-platform interactive whiteboard deployed in Geneva Schools, but I'm the only developer at this time so migrate to some modern technologies would be a dream I'm not sure I can place hope in (I guess it would result on a complete rewriting of the architecture, and it is a 300k+ lines of (old) code application at this time...). 

In its current state, a lot of things can be done with it (draw, write, embed C++ widgets, HTML apps, import images, sounds, videos, pdfs, record podcasts, ...) in the same scene. For HTML apps, I'm not sure  I can do the same thing without the webkit ; is there something allowing integrate HTML apps in my scene and interact with them like I can do it now, that is not QGraphicsWebView-based  ? 

![Capture d’écran de 2019-05-22 10-31-55](https://user-images.githubusercontent.com/11720903/58162659-e1f47d80-7c82-11e9-91bf-057c09d795ef.png)

**Comment by The-Compiler** [comment]
@kaamui There's a related [blogpost](https://blog.qt.io/blog/2017/01/19/should-you-be-using-qgraphicsview/) which might be interesting. Greetings from the German part of Switzerland! :wink:

**Comment by kaamui** [comment]
> @kaamui There's a related [blogpost](https://blog.qt.io/blog/2017/01/19/should-you-be-using-qgraphicsview/) which might be interesting. Greetings from the German part of Switzerland!

It was really interesting, thank you. Sadly I could not find any update since 2017 on this subject.

**Comment by annulen** [comment]
As there is no active development on QGraphicsView, I believe this blog post is still accurate.

>In its current state, a lot of things can be done with it (draw, write, embed C++ widgets, HTML apps, import images, sounds, videos, pdfs, record podcasts, ...) in the same scene. 

Embedding C++ widgets, as blog post hghlights, is a terrible idea performance-wise. If widgets are replaced with widget-like scene items, performance should increase a lot. However, if you don't care about performance and your main priority is keeping compatibility with existing widgets, then QGraphicsView may be an optimal solution, because QML / new scene graph don't provide "proxy widget" feature

**Comment by annulen** [comment]
BTW, I've updated https://github.com/annulen/webkit/wiki/Use-cases-of-QtWebKit with QGraphicsView use case, thanks for heads up!
