### ISSUE TITLE
Is qtwebkit still maintained by anyone ?

### ISSUE THREAD

**Issue by kaamui** [annulen/webkit#812]
Hello @annulen,

I would like to know the status of the qtwebkit branch. It seems to be stuck in the "alpha 2" step. Is qt blocking ? No more time for that ? 

Please tell me what's going on. It would be great if this information could be found somewhere in the wiki or in the FAQ or anywhere else.

Thanks.

**Comment by annulen** [comment]
> It seems to be stuck in the "alpha 2" step.

There were a lot of changes since alpha 2, please use tip of `qtwebkit-5.212` branch.

>Please tell me what's going on.

Content of `qtwebkit-5.212` branch is pretty much obsolete by now because it lags too much behind current state of WebKit upstream. 

I'm currently working on updating QtWebKit to curreent WebKit. It will take some time before some early preview version can be available. Wait for announcements!

Because of limited resources there are no plans to support any operating systems besides Linux, and it won't be supported as official Qt module. However, if there is substantial community funding, these decisions will be reconsidered.

**Comment by kaamui** [comment]
> Content of qtwebkit-5.212 branch is pretty much obsolete by now because it lags too much behind current state of WebKit upstream.

Comparing to the state of the last qtwebkit delivered by qt in 5.5, is it safe to use it ?

>I'm currently working on updating QtWebKit to curreent WebKit. It will take some time before some early preview version can be available. Wait for announcements!

Great news !

> However, if there is substantial community funding, these decisions will be reconsidered.

Can you bring more details on that please ?

**Comment by annulen** [comment]
>Comparing to the state of the last qtwebkit delivered by qt in 5.5, is it safe to use it ?

It's _eons_ ahead 5.5 version.

If something isn't working properly with 5.212 (there are a few known regressions), you might want to give a chance to the tip of 5.9 branch (it's basically the same WebKit branch as in 5.5, but with lots of bug fixes and security fixes).

>Can you bring more details on that please ?

See https://www.patreon.com/annulen (note that it's still unfinished)

**Comment by dugo** [comment]
Hi annulen,

I have an offer for you.

Can you give me a private contact email?

Thanks!

**Comment by annulen** [comment]
@dugo I'm not doing contract work. You can post your offer in QtWebKit mailing list and/or Qt-related resources, it can be that other community members are interested in such offers.

**Comment by annulen** [comment]
Related mailing lists:
webkit-qt@lists.webkit.org
interest@qt-project.org
webkit-jobs@lists.webkit.org

Also, qt.io forum: https://forum.qt.io/category/23/jobs

**Comment by dugo** [comment]
Ok, I understand.

But this is related with this repo and the patreon, it isn't a contract work.

Can you contact me?

**Comment by annulen** [comment]
OK, if it's really something which you don't want to publish in the open, you can contact me using my e-mail address from git history

**Comment by annulen** [comment]
Update: sufficient funds were collected. Stay tuned!

**Comment by Brouilles** [comment]
Hello,
Thank you for your approach.
Is there still a QTWebkit upgrade planned? In progress?

Because I am interested in replacing Blink (Electron app) with QT and especially Webkit. To use less resources and we are not a big fan of the Blink monopoly on Windows. And hoping to update otter-browser Webkit version (currently 602.1).

Thanks!

**Comment by annulen** [comment]
>Is there still a QTWebkit upgrade planned? In progress?
Yes, there is qtwebkit-dev-wip branch, and more work will be done there this month,

**Comment by RKesireddy2** [comment]
I am unable to setuserstylesheet() from localfile as posted in the forum https://forum.qt.io/topic/117470/qtwebkit-test-failures-to-load-setuserstylesheeturl-qurl-fromlocalfile-css after upgrading qt-webkit to 5.212 alpha 4. Is there any known issue or workaround to fix the same?

**Comment by annulen** [comment]
This is not an appropriate place for reporting new issues. Please open new issue.

**Comment by RKesireddy2** [comment]
> This is not an appropriate place for reporting new issues. Please open new issue.

Could you please let me know where could be raise new issues for Qt webkit? I raised the same in Qt forum or Qt webkit mailing list but didnot receive any response or feedback. Thanks.

**Comment by RKesireddy2** [comment]
Sorry opened a new issue https://github.com/qtwebkit/qtwebkit/issues/1021
